OHM-1059 update console dependencies
jembi/openhim-console pull request #529
Opened 2020-09-15 13:03 UTC by MattyJ007

2020-10-05 09:03 UTC, bradsawadye requested changes
There is an issue with the webpack dev-server. I could not get the app to run in dev mode

2020-10-16 12:29 UTC, MattyJ007 commented
@bradsawadye This functionality is broken on master... I'll find out what's wrong though and get it sorted here

2020-10-20 12:39 UTC, de-laz commented
@MattyJ007  LGTM 👍

2020-10-20 12:42 UTC, bradsawadye approved these changes

2020-10-20 12:44 UTC, merged