PLAT-707 Add kafka integration
jembi/openhim-console pull request #606
Opened 2023-04-06 10:52 UTC by nour-borgi

2023-05-08 11:05 UTC, michaelloosen commented on app/scripts/controllers/channel-tabs/routes.js
> +          return 'Not valid topic name! Only letters, numbers, . (dot), _ (underscore), - (minus) can use used!'
```suggestion
          return 'Not valid topic name! Only letters, numbers, . (dot), _ (underscore), - (minus) can be used!'
```

2023-05-17 13:57 UTC, rcrichton commented on app/views/partials/channels-tab-routes.html
> +        <i ng-show="uiSettings.showTooltips" uib-tooltip="Request will be sent to the second route unless the response status of the primary route match one of these status codes. A single value or a
```suggestion
        <i ng-show="uiSettings.showTooltips" uib-tooltip="Request will NOT be sent to the second route unless the response status of the primary route match one of these status codes. A single value or a list are both accepted. A list should be comma separated (single status codes e.g. 200,201, range e.g. 2**,3**,  mixture of both e.g. 204,3**)." class="glyphicon glyphicon-question-sign tooltip-wide" style="font-size: 12px"></i>
```

2023-05-17 13:58 UTC, rcrichton commented on app/views/partials/channels-tab-routes.html
> +        <i ng-show="uiSettings.showTooltips" uib-tooltip="Request will be sent to the second route unless the response status of the primary route match one of these status codes. A single value or a
```suggestion
        <i ng-show="uiSettings.showTooltips" uib-tooltip="Request will NOT be sent to the secondary route(s) unless the response status of the primary route match one of these status codes. A single value or a list are both accepted. A list should be comma separated (single status codes e.g. 200,201, range e.g. 2**,3**,  mixture of both e.g. 204,3**)." class="glyphicon glyphicon-question-sign tooltip-wide" style="font-size: 12px"></i>
```

2023-05-17 14:40 UTC, rcrichton commented
Overall this appears to be working very well! Nice job all!

2023-05-18 07:22 UTC, rcrichton requested changes
Looks good make some comments above.

2023-05-29 15:16 UTC, bradsawadye approved these changes

2023-05-30 09:29 UTC, bradsawadye approved these changes

2023-05-30 09:30 UTC, merged