feat: add docker file for Google Cloud Run
jembi/openhim-console pull request #610
Opened 2023-05-19 12:56 UTC by marrouchi

# Motivation

Google Cloud Run does not offer a way to mount volumes nor configs, as it supports only stateless containers.

2023-05-19 13:09 UTC, michaelloosen submitted a review, later dismissed

2023-05-19 14:47 UTC, rcrichton requested changes
With the above changes, I see no reason why this couldn't be the default docker image as it would be fully backwards compatible. Maybe we should consider that?

2023-05-19 14:47 UTC, rcrichton commented on infrastructure/google-cloud-run/start-nginx.sh
> +cat config/default-env.json | envsubst $EXISTING_VARS | tee config/default.json
If you are selecting all var, isn't that the same as running `envsubst` with no parameters?

2023-05-19 14:47 UTC, rcrichton commented on app/config/default-env.json
Should we rather have env vars for all option in this file. The shell script might have to ensure the env vars are set with a default value where needed. i.e. `export PROTOCOL=${PROTOCOL:-https}` or something.

2023-05-19 17:15 UTC, marrouchi commented on app/config/default-env.json
> +  "ssoEnabled": ${KC_OPENHIM_SSO_ENABLED},
```suggestion
  "ssoEnabled": ${KC_OPENHIM_SSO_ENABLED},
```
@michaelloosen  in platform this value is within double quotes, as string it's evaluated to "true".

2023-05-22 09:21 UTC, arran-standish approved these changes
I like the idea of updating the base image instead as this simplifies platform, as currently it is maintaining a default.json file that it does envsubst on. Which means we have the same file duplicated across repo's that we need to keep in sync. With this change we can remove all that from platform and just pass in the relevant environment variables

2023-05-25 09:53 UTC, michaelloosen approved these changes

2023-05-25 09:54 UTC, merged