TB-218 OpenHIM Portal page shell
jembi/openhim-console pull request #618
Opened 2023-10-23 09:20 UTC by medchedli

These changes require updating the DB Schema. Check  →   jembi/openhim-core-js#1212

2023-10-25 15:03 UTC, nour-borgi commented on packages/portal-app/package.json
> +    "@types/webpack-env": "^1.16.2",
These should be dev dependency

2023-10-30 08:58 UTC, MatthewErispe requested changes

2023-10-30 08:58 UTC, MatthewErispe commented on packages/header-app/src/root.component.tsx
> +import {ListItemIcon} from '@mui/material'
@medchedli can this be added to line 11?

2023-10-30 08:58 UTC, MatthewErispe commented on packages/portal-app/src/components/AppCard/AppCard.tsx
> +                  /*
@medchedli do you need this?

2023-10-30 08:58 UTC, MatthewErispe commented on packages/portal-app/src/utils/apiClient.ts
> +const API_URL = 'https://localhost:8080/'
@medchedli can this be configured as a evironment variable?

2023-11-01 13:33 UTC, bradsawadye commented on packages/header-app/src/root.component.tsx
> +                    <AppsIcon></AppsIcon>
```suggestion
                    <AppsIcon/>
```

2023-11-01 13:33 UTC, bradsawadye commented on packages/header-app/src/root.component.tsx
> +                    <LogoutIcon></LogoutIcon>
```suggestion
                    <LogoutIcon/>
```

2023-11-01 13:38 UTC, bradsawadye commented on packages/portal-app/.prettierignore
> +pnpm-lock.yaml
```suggestion
pnpm-lock.yaml

```

2023-12-01 08:22 UTC, MatthewErispe approved these changes

2023-12-08 13:00 UTC, merged