Modify Openhim core api package to fetch core url from default.json file
jembi/openhim-console pull request #632
Opened 2024-05-24 10:41 UTC by drizzentic

2024-05-24 10:41 UTC, rcrichton commented
Task linked: [CU-86bywx2j0 SSO isn't enabled on the OpenHIM console anymore when enabled via env vars](https://app.clickup.com/t/86bywx2j0)

2024-05-24 12:02 UTC, rcrichton requested changes
Looks good, a few comments.

Also we can remove the old Dockerfile in the root and we can also remove this copied file - https://github.com/jembi/openhim-console/blob/CU-86bywx2j0_SSO-isnt-enabled-on-the-OpenHIM-console-anymore-when-enabled-via-env-vars/config/default-env.json

2024-05-24 12:55 UTC, rcrichton commented on packaging/import-maps-server/Dockerfile-mf
Looks like the above line need to be updated too.

2024-05-24 13:53 UTC, drizzentic commented on packages/openhim-core-api/src/jembi-openhim-core-api.ts
> +  await initializationPromise;
This ensures that the right url is set before any of the endpoints can be called.

2024-05-24 14:09 UTC, drizzentic commented on packages/openhim-core-api/src/jembi-openhim-core-api.ts
> +  }
For consistency I think we should have the check across all functions to ensure that same behavior is cascaded.

2024-05-27 13:53 UTC, rcrichton requested changes
Looks good to me, just a final comment I still see a few references to `REACT_APP_OPENHIM_API_BASE_URL` if I do a global search. I think those can be removed now right?

![image](https://github.com/jembi/openhim-console/assets/266576/0927690f-9030-4b68-84c4-8bd3ef53c87b)

2024-05-28 08:18 UTC, rcrichton approved these changes
LGTM

2024-05-28 08:35 UTC, merged