fx: Styling issues
jembi/openhim-console pull request #690
Opened 2024-09-30 13:51 UTC by brett-onions

Resolving the following tickets:

86c0fe6na: Navbar: remove padding around
86c08q705: Header is bigger than the other pages and logo is off center
86c0fe27p: Logo: image used is cropped to tightly

2024-09-30 13:51 UTC, rcrichton commented
Task linked: [CU-86c08q705 Header is bigger than the other pages and logo is off center](https://app.clickup.com/t/86c08q705)

2024-10-01 14:08 UTC, drizzentic requested changes

2024-10-01 14:08 UTC, drizzentic commented on packages/header-app/src/header-styles.css
> +}
Do we still need this file?

2024-10-01 14:08 UTC, drizzentic commented on packages/header-app/src/root.component.tsx
> +import './header-styles.css'
Seems it's not being used

2024-10-01 14:08 UTC, drizzentic commented on packages/header-app/src/components/openhim.appbar.component.tsx
> +        // borderBottom: '1px solid #e0e0e0',
We should probably discard this properties

2024-10-01 14:38 UTC, drizzentic approved these changes

2024-10-01 14:53 UTC, merged