feat: add permissions.
jembi/openhim-console pull request #694
Opened 2024-10-03 17:06 UTC by marvinIsSacul

2024-10-03 17:07 UTC, rcrichton commented
Task linked: [CU-86c0bkuhz Conditionally show the menu items based on the permissions the user has](https://app.clickup.com/t/86c0bkuhz)

2024-10-07 07:34 UTC, drizzentic requested changes

2024-10-07 07:43 UTC, marvinIsSacul commented on packages/header-app/src/types/index.ts
> +  'metadata-manage-all': boolean
Done.

2024-10-07 10:25 UTC, drizzentic commented on packages/header-app/src/components/openhim.appbar.component.tsx
```suggestion
    if (window.location.href.includes('#!/login')) return
```

2024-10-07 10:46 UTC, drizzentic approved these changes
LGTM!

2024-10-07 11:06 UTC, merged