Ci 86c0jz8p7 basic info validation
jembi/openhim-console pull request #710
Opened 2024-10-31 12:59 UTC by marvinIsSacul

2024-11-06 06:51 UTC, drizzentic requested changes

2024-11-06 06:51 UTC, drizzentic commented on packages/users-app/src/screens/create.user.component.tsx
> +          }}
We need to adapt this to the new Base template

2024-11-06 06:51 UTC, drizzentic commented on packages/users-app/src/screens/list.users.screen.tsx
> +          >
Adapt to new basetemplate

2024-11-07 05:02 UTC, marvinIsSacul commented
Task linked: [https://app.clickup.com/t/86c0j3aan](https://app.clickup.com/t/86c0j3aan)

2024-11-07 07:20 UTC, marvinIsSacul commented on packages/users-app/src/components/common/basic.info.component.tsx
> +                    label="Auto-update Transaction LisshowTooltipst."
Yea. Fixed it now.

2024-11-12 11:44 UTC, drizzentic approved these changes
LGTM!

2024-11-12 12:07 UTC, merged